### ISSUE TITLE
-Incorporate front-end to update unretrievable data (states, etc.)

### ISSUE THREAD

**Issue by minhta16** [minhta16/ITSSamanageEnhancement#35]

**Comment by nguyentruong17** [comment]
I was thinking about this ytd
We have 2 unretrievable data: state and priority
I was thinking of having an "Add/Remove" Button in the Settings/Database Tab. However, I dont think everyone should have the access to that button, so I don't know how to implement it properly (it must have something to do with the token because from the token, we get the user, and only certain types of users can have this ability to add/remove state and priority)

**Comment by minhta16** [comment]
This add/remove functionality wouldn't change the database in any ways so it doesn't matter what rights the user has. They should all be able to change state/priority.
